[General]
    root_dir = "/home/mo/noa_excel"
    success_strig = "Time For Coffee"

[SourceDataSheets]
    data_path = "metro-gint-240515.xlsx"
    sheet_names = ["POINT", "LITHOLOGY"]
    id_column_title = "PointID"

    POINT = ["PointID", "Elevation", "HoleDepth", "North", "East"]
    LITHOLOGY = ["PointID", "Depth"]

[DestinationDataSheets]
    folder_path = "destination"
    file_prefix = ""

    #Sheets.POINT.North = "=IF(Elevation>10, 10, Elevation)"
    Sheets.POINT.Elevation = "=IF(HoleDepth>62, 62, HoleDepth)"
    
    Sheets.LITHOLOGY.Bottom = "=IF(Depth>1, 1, Depth)"

[IdsSheet]
    path = "ids.xlsx"
    sheet_name = "POINT" 
    id_column_title = "S6"
    id_pattern = "([a-zA-Z]+[0-9]+-)+[a-zA-Z]?"